name: django ecs ci/cd

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pyton -m pip install --upgrade pip
          pip install django
          pip install djangorestframework
      #Docker-compose
      - name: Build Docker Compose
        run: docker-compose
